spring.application.name=issuetracker
database-name=issuetracker
spring.datasource.url=jdbc:postgresql://localhost:5432/${database-name}
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false